Add ssd health pre-check for warm-reboot (#4086)
* Add ssd health pre-check for warm-reboot

Signed-off-by: Boyang Yu <byu@arista.com>

* Move to function check_ssd_health and run it earlier

Signed-off-by: Boyang Yu <byu@arista.com>

---------

Signed-off-by: Boyang Yu <byu@arista.com>

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -25,6 +25,7 @@ DEVPATH="/usr/share/sonic/device"
 PLATFORM=$(sonic-cfggen -H -v DEVICE_METADATA.localhost.platform)
 PLATFORM_PLUGIN="${REBOOT_TYPE}_plugin"
 LOG_SSD_HEALTH="/usr/local/bin/log_ssd_health"
+SSD_UTIL="/usr/local/bin/ssdutil"
 PLATFORM_FWUTIL_AU_REBOOT_HANDLE="platform_fw_au_reboot_handle"
 PLATFORM_REBOOT_PRE_CHECK="platform_reboot_pre_check"
 SSD_FW_UPDATE="ssd-fw-upgrade"
@@ -50,6 +51,7 @@ EXIT_TEAMD_RETRY_COUNT_FAILURE=23
 EXIT_NO_MIRROR_SESSION_ACLS=24
 EXIT_PFC_STORM_DETECTED=25
 EXIT_LEFTOVER_CPA_TUNNEL=30
+EXIT_SSD_HEALTH_FAILURE=40
 
 [ -f /usr/share/sonic/device/$PLATFORM/asic.conf ] && . /usr/share/sonic/device/$PLATFORM/asic.conf
 NUM_ASIC=${NUM_ASIC:-1}
@@ -744,6 +746,31 @@ function check_pfc_storm_active()
     fi
 }
 
+function check_ssd_health()
+{
+    if [ -x "${SSD_UTIL}" ]; then
+        debug "Checking ssd health before ${REBOOT_TYPE}..."
+        health_line=$(${SSD_UTIL} | grep -E "Health\s*:\s*[0-9]+\.?[0-9]*%" || true)
+
+        if [ -z "$health_line" ]; then
+            debug "Warning: Health line not found in ${SSD_UTIL} output."
+        else
+            # Extract the numeric value X from "Health       : X%"
+            health_value=$(echo "$health_line" | sed -n 's/[^0-9]*\([0-9]\+\).*/\1/p')
+
+            # Check if health_value is a valid number
+            if [ -z "$health_value" ]; then
+                debug "Warning: Could not find health percentage."
+            elif [ "$health_value" -gt 0 ]; then
+                debug "SSD Health is $health_value% — OK."
+            else
+                error "Warning: Health is $health_value% — Possible drive failure!"
+                exit "${EXIT_SSD_HEALTH_FAILURE}"
+            fi
+        fi
+    fi
+}
+
 function check_db_integrity()
 {
     if [[ "$REBOOT_TYPE" = "warm-reboot" || "$REBOOT_TYPE" = "fastfast-reboot" || "$REBOOT_TYPE" = "express-reboot" || "$REBOOT_TYPE" = "fast-reboot" ]]; then
@@ -764,6 +791,7 @@ function check_db_integrity()
 function reboot_pre_check()
 {
     execute_in_namespaces asic check_pfc_storm_active
+    check_ssd_health
     check_docker_exec
     # Make sure that the file system is normal: read-write able
     filename="/host/test-$(date +%Y%m%d-%H%M%S)"
