[DPU] Add optional DPU flow dump to techsupport collection
Signed-off-by: Vivek Reddy <vkarri@nvidia.com>

diff --git a/scripts/generate_dump b/scripts/generate_dump
--- a/scripts/generate_dump
+++ b/scripts/generate_dump
@@ -53,6 +53,8 @@ DEBUG_DUMP=false
 ROUTE_TAB_LIMIT_DIRECT_ITERATION=24000
 IS_SUPERVISOR=false
 
+ENABLE_FLOW_DUMP=false
+
 # lock dirs/files
 LOCKDIR="/tmp/techsupport-lock"
 PIDFILE="${LOCKDIR}/PID"
@@ -2478,6 +2480,62 @@ save_gearbox_data() {
 }
 
 ###############################################################################
+# Save DPU Flow Dump for better debugging
+###############################################################################
+start_dpu_flow_dump() {
+    trap 'handle_error $? $LINENO' ERR
+    if [[ "${ENABLE_FLOW_DUMP}" != true ]]; then
+        return
+    fi
+
+    if $NOOP; then
+        return
+    fi
+
+    if [[ ! -f /usr/local/bin/sonic-dpu-flow-dump.py ]]; then
+        echo "INFO: sonic-dpu-flow-dump.py not found, skipping DPU flow dump collection." >&2
+        return
+    fi
+
+    local is_dpu
+    is_dpu=$(python3 -c "from sonic_py_common import device_info; print(device_info.is_dpu())" 2>/dev/null) || is_dpu="False"
+    if [[ "$is_dpu" != "True" ]]; then
+        return
+    fi
+
+    if [ ! -d $LOGDIR ]; then
+        $MKDIR $V -p $LOGDIR
+    fi
+
+    echo "Started DPU flow dump collection (pid ${BASHPID})."
+
+    local start_t=$(date +%s%3N)
+    local path_file stderr_file
+    path_file=$(mktemp /tmp/ts_dpu_flow_dump_path.XXXXXX)
+    stderr_file=$(mktemp /tmp/ts_dpu_flow_dump_err.XXXXXX)
+    sonic-dpu-flow-dump.py --no-flow-state --file-only > "$path_file" 2>"$stderr_file"
+    local rc=$?
+    if [[ "$rc" -eq 0 ]] && [[ -f "$path_file" ]]; then
+        echo "DPU flow dump collection successful (rc=${rc})."
+        local src
+        src=$(tr -d '\n\r' < "$path_file")
+        if [[ -n "$src" && -f "$src" ]]; then
+            $MV "$src" $LOGDIR
+            echo "DPU flow dump saved: $LOGDIR/$(basename "$src")"
+        fi
+    else
+        if [[ -f "$stderr_file" ]]; then
+            echo "DPU flow dump collection failed (rc=${rc}). Stderr: $stderr_file"
+        else
+            echo "DPU flow dump collection failed or skipped (rc=${rc})."
+        fi
+    fi
+    $RM -f "$path_file" "$stderr_file"
+    local end_t=$(date +%s%3N)
+    echo "[ dpu_flow_dump ] : $(($end_t-$start_t)) msec" >> $TECHSUPPORT_TIME_INFO
+}
+
+###############################################################################
 # Main generate_dump routine
 # Globals:
 #  All of them.
@@ -2700,6 +2758,7 @@ main() {
         collect_pensando
     fi
 
+    start_dpu_flow_dump &
 
     # 2nd counter snapshot late. Need 2 snapshots to make sense of counters trend.
     save_counter_snapshot $asic 2
@@ -2886,7 +2945,7 @@ abort() {
 ###############################################################################
 usage() {
     cat <<EOF
-$0 [-xnvh]
+$0 [-xnvhf]
 
 Create a SONiC system dump for support/debugging. Requires root privileges.
 
@@ -2915,11 +2974,12 @@ OPTIONS
         Redirect any intermediate errors to STDERR
     -d
         Collect the output of debug dump cli
+    -f
+        On DPU platforms, also collect a DPU flow dump
 EOF
 }
 
-
-while getopts ":xnvhzas:t:r:d" opt; do
+while getopts ":xnvhzas:t:r:df" opt; do
     case $opt in
         x)
             # enable bash debugging
@@ -2969,6 +3029,9 @@ while getopts ":xnvhzas:t:r:d" opt; do
             ;;
         d)
             DEBUG_DUMP=true
+            ;;
+        f)
+            ENABLE_FLOW_DUMP=true
             ;;
         /?)
             echo "Invalid option: -$OPTARG" >&2
